version: '1.0'

services:
  db:
    image: postgres:14-alpine
    container_name: vinhunilab
    restart: always
    environment:
      POSTGRES_USER: vinhunilab_db
      POSTGRES_PASSWORD: vinhunilab_db@123
      POSTGRES_DB: vinhunilab_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
